
<MsgToApp>:
    MDBoxLayout:
        orientation:'vertical'
        MDToolbar:
            title:'Mensagem'
        MDBoxLayout:
            FloatLayout:
                MDCard:
                    orientation:'vertical'
                    size_hint:.9,None
                    height:'400dp'
                    padding:'5dp'
                    radius:10,10,10,10
                    pos_hint:{'center_x':.5,'top':.9}
                    MDLabel:
                        size_hint_y:None
                        height:'30dp'
                        text:'"Aviso importante!"'
                        color:0,0,0,.4
                        id:warning
                    MDSeparator:
                    ScrollView:
                        MDLabel:
                            text:'Atualize seu app Atualização importante'
                            halign:'center'
                            id:msg
                            color:0,0,0,1
                    MDTextButton:
                        size_hint_y:None
                        height:'30dp'
                        id:link
                        text:'http://Link de atualização'
                        color:0,0,0,1

                MDRaisedButton:
                    text:'OK'
                    pos_hint:{'center_x':.5,'center_y':.3}
#                    on_release:root.set_msg()